server:
    port: 80

# mysql 属性配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: root




# 打印日志
mybatis:
    mapper-locations: classpath*:mybatis/*.xml
    type-aliases-package: com.springboot.demo
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

